### ISSUE TITLE
3440x1440, fix dont work and show error

### ISSUE THREAD

**Issue by crystallon** [Lyall/SyberiaTWBFix#5]
![syb1](https://user-images.githubusercontent.com/54250875/170375066-4044d11d-bf58-48e5-80cb-8544fa3f3df5.png)
![syb2](https://user-images.githubusercontent.com/54250875/170375073-450722ed-0d20-4069-bdeb-77ade2101e9c.png)

**Comment by Lyall** [comment]
You're using an old game version which is incompatible with the latest fix. You need to update your pirated copy of the game or buy it legitimately. I'm going to close this issue now.
